# Generated by Django 4.2.3 on 2023-07-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='designation',
        ),
        migrations.AddField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(default='Trainee', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
