# Generated by Django 4.2.3 on 2023-07-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_role_alter_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(default='Trainee', max_length=1000),
        ),
    ]
