# Generated by Django 4.2.3 on 2023-07-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(max_length=1000),
        ),
    ]
