# Generated by Django 4.2.3 on 2023-07-13 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_delete_role_alter_employee_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
